modLoader="javafml"
loaderVersion="[4,)"
license="GNU Lesser General Public License version 2.1 (LGPLv2.1)"

[[mods]]
modId="sculks_of_arda"
version="1.4.3.4"
displayName="Arda's Sculks"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Good Games."
authors="Arda"
description="Arda's Sculk mod is a mod that allows you to make stronger tools and items by improving the sculks in the game.  "

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.sculks_of_arda]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.sculks_of_arda]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.sculks_of_arda]]
    modId="geckolib"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sculks_of_arda]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sculks_of_arda]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration